[
  {
    name: "Margherita",
    category: "Pizza",
    Mini: 6.1,
    Medium: 7.5,
    Maxi: 14.3,
    Pan: 6.9,
    description: "Mit fruchtiger Tomatensauce, und zartschmelzendem Käse",
    imageUrl: "Margherita.jpg",
  },
  {
    name: "Salami",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Herzhaft Rindersalami (100% Rind Chili), Käse",
    imageUrl: "Salami.jpg",
  },
  {
    name: "Peperoniwurst",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Leckere Peperoniwurst, Käse",
    imageUrl: "Peperoniwurst.jpg",
  },
  {
    name: "Schinken",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Schinken (100% Puten Schinken), Käse",
    imageUrl: "Schinken.jpg",
  },
  {
    name: "Tonno",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Thunfisch, rote Zwiebeln, Knoblauch, Käse",
    imageUrl: "Tonno.jpg",
  },
  {
    name: "Lover",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Schinken, frische Champignons, Käse",
    imageUrl: "Lover.jpg",
  },
  {
    name: "Bayern",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Peperoniwurst, rote Zwiebeln, Käse",
    imageUrl: "Bayern.jpg",
  },
  {
    name: "Hawaii",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Puten Schinken, Ananas, Käse",
    imageUrl: "Hawaii.jpg",
  },
  {
    name: "Downtown",
    Mini: 6.7,
    Medium: 9.8,
    Maxi: 16.5,
    Pan: 8.9,
    description: "Salami (100% Rind), Schinken, frische Champignons, Käse",
    imageUrl: "Downtown.jpg",
  },
  {
    name: "French Cheese",
    Mini: 7.3,
    Medium: 10.8,
    Maxi: 19.5,
    Pan: 9.9,
    description: "Gouda, Mozzarella, Gorgonzola, Fetakäse",
    imageUrl: "French Cheese.jpg",
  },
  {
    name: "City",
    Mini: 7.3,
    Medium: 10.8,
    Maxi: 19.5,
    Pan: 9.9,
    description: "Puten Schinken, Rindersalami, Champignons, Käse",
    imageUrl: "City.jpg",
  },
  {
    name: "Star",
    Mini: 7.3,
    Medium: 10.8,
    Maxi: 19.5,
    Pan: 9.9,
    description: "Frische Paprika, rote Zwiebeln, Schinken, Salami, Käse",
    imageUrl: "Star.jpg",
  },
  {
    name: "Wow",
    Mini: 7.3,
    Medium: 10.8,
    Maxi: 19.5,
    Pan: 9.9,
    description: "Sauce Hollandaise, Broccoli, Hähnchenbrustfilet",
    imageUrl: "Wow.jpg",
  },
  {
    name: "Slice",
    Mini: 7.3,
    Medium: 10.8,
    Maxi: 19.5,
    Pan: 9.7,
    description:
      "Sauce Hollandaise, Hähnchenbrustfilet, Cherrytomaten, rote Zwiebeln, Käse",
    imageUrl: "Slice.jpg",
  },
  {
    name: "Diavolo",
    description: "Salami, Peperoniwurst, Schinken, Peperoni, Zwiebeln, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Diavolo.jpg",
  },
  {
    name: "Half/Half",
    description: "Für Doppelt genießer 2 Pizzen nach Wahl, Auf einer Pizza",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Half/Half.jpg",
  },
  {
    name: "Chic",
    description:
      "Salsa Sauce, rote zwiebeln, frische Tomaten, Peperoni, Paprika, Mais, Champignons, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Chic.jpg",
  },
  {
    name: "Vegetaria",
    description:
      "Broccoli, frische Champignons, frische Tomaten, Mais, frische Paprika, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Vegetaria.jpg",
  },
  {
    name: "Mango",
    description: "Peperoniwurst, Mais, Zwiebeln, Paprika, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Mango.jpg",
  },
  {
    name: "Bella",
    description: "Frische Tomaten, Mozzarella, frische Basilikum, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Bella.jpg",
  },
  {
    name: "Power",
    description:
      "Peperoniwurst (100% Rind Chili) rote Zwiebeln, Oliven, Peperoni, scharfe Sauce, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Power.jpg",
  },
  {
    name: "Bolognese",
    description:
      "Tomaten-Rind Hackfleisch Sauce, Spaghetti, mit Käse überbacken",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Bolognese.jpg",
  },
  {
    name: "Sucuk",
    description: "Sucuk (100% Rind), Paprika, rote Zwiebeln, Weichkäse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Sucuk.jpg",
  },
  {
    name: "BBQ",
    description:
      "Rinderhackfleisch (100% Rind), milde Peperoni, Mais, rote Zwiebeln, anschließend BBQ Sauce, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "BBQ.jpg",
  },
  {
    name: "Pizza Zoo",
    description: "Fleisch, Sucuk, Fetakäse, rote Zwiebeln, Jalapenos, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Pizza Zoo.jpg",
  },
  {
    name: "Brano Mia",
    description: "BBQ Sauce, Hähnchenfilet, Mais, Paprika, rote Zwiebeln, Käse",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Brano Mia.jpg",
  },
  {
    name: "Premium",
    description:
      "Peperoniwurst, frische Tomaten, frische Basilikum, Mozzarella",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Premium.jpg",
  },
  {
    name: "Döner",
    description: "Döner Fleisch, rote Zwiebeln, Käse, Aioli Dip",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Döner.jpg",
  },
  {
    name: "Pizza Land",
    description: "Truthanschinken, Champignons, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 21.5,
      Pan: 9.9,
    },
    imageUrl: "Pizza Land.jpg",
  },
  {
    name: "Firebox",
    description: "Rote Zwiebeln, 100% Kinderhackfleisch, Eier, Käse",
    prices: {
      Mini: 7.9,
      Medium: 11.1,
      Maxi: 11.1,
      Pan: 9.9,
    },
    imageUrl: "Firebox.jpg",
  },
  {
    name: "Moon",
    description:
      "Geheimnisvolle scharfe Sauce, Chili, Salami (100% Rind), rote Zwiebeln, schwarze Oliven, milde Peperoni",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Moon.jpg",
  },
  {
    name: "Burger",
    description:
      "Rinderhackfleisch (100% Rind), frische Tomaten, Essig Gurken, rote Zwiebeln, anschließend Burger Sauce",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Burger.jpg",
  },
  {
    name: "Joker",
    description: "Sauce Hollandaise, Lachs filet, Spinat, Käse",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Joker.jpg",
  },
  {
    name: "Fresh Slice",
    description:
      "Salami (100% Rind), Mais, Paprika, Thunfisch, Jalapenos, rote Zwiebeln, Käse",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Fresh Slice.jpg",
  },
  {
    name: "Palace",
    description: "Sauce Hollandaise, geflügelwürstchen (100% Geflügel), Mais",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Palace.jpg",
  },
  {
    name: "Broadway",
    description: "Truthanschinken, 100% Rindersalami, Käse",
    prices: {
      Mini: 8.3,
      Medium: 12.1,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Broadway.jpg",
  },
  {
    name: "Crispy Slices",
    description: "100% Rindersalami, Peperoniwurst, Truthanschinken, Käse",
    prices: {
      Mini: 8.3,
      Medium: 11.4,
      Maxi: 21.5,
      Pan: 10.9,
    },
    imageUrl: "Crispy Slices.jpg",
  },
  {
    name: "Bliss",
    description: "Paprika, rote Zwiebeln, Hähnchengyros, Käse",
    prices: {
      Mini: 8.4,
      Medium: 11.4,
      Maxi: 21.5,
      Pan: 10.1,
    },
    imageUrl: "Bliss.jpg",
  },
  {
    name: "Slice of Heaven",
    description: "Tomaten, on the top rucola, Parmesan",
    prices: {
      Mini: 8.4,
      Medium: 11.4,
      Maxi: 21.5,
      Pan: 10.1,
    },
    imageUrl: "Slice of Heaven.jpg",
  },
  {
    name: "Extra Zutat",
    prices: {
      Mini: "+0,80",
      Medium: "+1,30",
      Maxi: "+2,30",
      Pan: "+1,00",
    },
    imageUrl: "Extra Zutat.jpg",
  },
];
